#server.port=8080
#server.error.include-message=never
#server.error.include-binding-errors=never
#
## CORS para desarrollo: aceptar cualquier origen (incluido file://)
#spring.web.cors.allowed-origins=*
#spring.web.cors.allowed-methods=GET,POST,OPTIONS
#spring.web.cors.allowed-headers=Content-Type,Accept
#
## Configuración H2 / JPA (en memoria para desarrollo)
#spring.datasource.url=jdbc:h2:mem:portfolio-db;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.profiles.active=dev